name: platform-${ACTIVE_ENV:-prod}
services:
  frontend-admin:
    container_name: frontend-admin-${ACTIVE_ENV:-prod}
    image: frontend-admin:0.0.1
    build:
      context: ../../
      dockerfile: resources/docker/Dockerfile.frontend_admin
    restart: unless-stopped
    networks:
      - default-network
  # steins-app:
  #   container_name: steins-app-${SPRING_ACTIVE:-prod}
  #   image: steins-app:0.0.4
  #   build:
  #     context: ../../
  #     dockerfile: resources/docker/Dockerfile.backend
  #   environment:
  #     - NACOS_SERVER_ADDR=${NACOS_SERVER_ADDR:-host.docker.internal}
  #     - NACOS_USERNAME=${NACOS_USERNAME:-nacos}
  #     - NACOS_PASSWORD=${NACOS_PASSWORD:-nacos}
  #     - SW_AGENT_COLLECTOR_BACKEND_SERVICES=${SW_AGENT_COLLECTOR_BACKEND_SERVICES:-host.docker.internal:11800}
  #     - SW_AGENT_NAME=${SW_AGENT_NAME:-prod_steins_admin}
  #     - JAVA_OPTS=${JAVA_OPTS}
  #     - SPRING_ACTIVE=${SPRING_ACTIVE:-prod}
  #   restart: unless-stopped
  #   ports:
  #     - ${STEINS_APP_PORT:-18001}:18001
  #   networks:
  #     - default-network
  
  platform-nginx:
    container_name: platform-nginx-${ACTIVE_ENV:-prod}
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/nginx:1.18.0-alpine
    command: ["nginx", "-c", "/etc/nginx/nginx.conf", "-g", "daemon off;"]
    ports:
      - 18080:18080
    volumes:
      - ${NGINX_VOLUME_LOG:-./logs/nginx}:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default-network
networks:
  default-network:
    name: platform-network-${SPRING_ACTIVE:-prod}
    driver: bridge
