name: forty-middle
services:
  
  mysql:
    container_name: forty-mysql
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/mysql:8.0.41
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_VOLUME_LOG:-./data/mysql/logs}:/var/log/mysql
      - ${MYSQL_VOLUME_DATA:-./data/mysql/data}:/var/lib/mysql
      - ${MYSQL_VOLUME_CONF:-./data/mysql/conf}:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
    restart: always
    networks:
      - middle-network

  # redis:
  #   container_name: forty-redis
  #   image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/redis:5.0.14
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ${REDIS_VOLUME_DIRECTORY:-.}:/data
  #     - ${REDIS_VOLUME_CONFIG:-./redis.conf}:/etc/redis/redis.conf
  #   command: redis-server /etc/redis/redis.conf
  #   networks:
  #     - middle-network

networks:
  middle-network:
    external: true
    name: platform-shared-net
