name: platform-application
services:
  frontend-admin:
    container_name: frontend-admin
    image: frontend-admin:0.0.1
    build:
      context: ../../
      dockerfile: resources/docker/Dockerfile.frontend_admin
    restart: unless-stopped
    networks:
      - default-network
  platform-backend:
    container_name: platform-backend
    image: platform-backend:0.0.1
    build:
      context: ../../
      dockerfile: resources/docker/Dockerfile.backend
    volumes:
      - ${BACKEND_LOG:-./logs/server}:/app/logs
    restart: unless-stopped
    environment:
      - FORTY_APP_MYSQL_HOST=forty-mysql
      - FORTY_APP_PORT=8080
      - FORTY_APP_MYSQL_DB=${FORTY_APP_MYSQL_DB}
      - FORTY_APP_MYSQL_USER=${FORTY_APP_MYSQL_USER:-root}
      - FORTY_APP_MYSQL_PASSWORD=${FORTY_APP_MYSQL_PASSWORD:-123456}
      - FORTY_APP_REDIS_HOST=forty-redis
      - FORTY_APP_REDIS_PASSWORD=${FORTY_APP_REDIS_PASSWORD:-}
      - WECHAT_APP_ID=${WECHAT_APP_ID}
      - WECHAT_APP_SECRET=${WECHAT_APP_SECRET}
      - SUPER_BED_TOKEN=${SUPER_BED_TOKEN}
    networks:
      - default-network
  
  platform-nginx:
    container_name: platform-nginx
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/nginx:1.18.0-alpine
    command: ["nginx", "-c", "/etc/nginx/nginx.conf", "-g", "daemon off;"]
    ports:
      - 18080:18080
    volumes:
      - ${NGINX_VOLUME_LOG:-./logs/nginx}:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default-network
networks:
  default-network:
    external: true
    name: platform-shared-net
