FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/node:22.21.0 AS builder

WORKDIR /build

COPY steins-frontend-admin .

RUN sed -i '/"electron":/d' package.json && rm -f yarn.lock && yarn && npm run build

FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/nginx:1.18.0-alpine

WORKDIR /app

COPY --from=builder /build/build .

COPY resources/docker/frontend_admin_nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]