name: forty-middle
services:
  
  mysql:
    container_name: forty-mysql
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/mysql:8.0.41
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_VOLUME_LOG:-./data/mysql/logs}:/var/log/mysql
      - ${MYSQL_VOLUME_DATA:-./data/mysql/data}:/var/lib/mysql
      - ${MYSQL_VOLUME_CONF:-./data/mysql/conf}:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
    restart: always
    networks:
      - middle-network

  redis:
    container_name: forty-redis
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/quay.io/opstree/redis:v7.0.5
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-123456}
      - REDIS_APPENDONLY=yes
      - REDIS_MAXMEMORY=256mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    volumes:
      - ${REDIS_VOLUME_DIRECTORY:-.}:/data
    command: redis-server /etc/redis/redis.conf
    networks:
      - middle-network

networks:
  middle-network:
    external: true
    name: platform-shared-net
